
// JSP 하드코딩된 메뉴 구조를 그대로 변환한 데이터
export const MENU_DATA = [
  {
    id: 1,
    name: "공지사항",
    path: "/notice",
    upperId: 0,
    depth: 1,
    seq: 1,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 2,
    name: "상담하기",
    path: "",
    upperId: 0,
    depth: 1,
    seq: 2,
    useFlag: 1,
    isLeaf: 0,
    centerId: 0,
    isOpen: true,
  },
  {
    id: 3,
    name: "콜",
    path: "/counselor/counselingCall",
    upperId: 2,
    depth: 2,
    seq: 1,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 4,
    name: "채팅",
    path: "/counselor/counselingChat",
    upperId: 2,
    depth: 2,
    seq: 2,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 5,
    name: "게시판",
    path: "/counselor/counselingBoard",
    upperId: 2,
    depth: 2,
    seq: 3,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 6,
    name: "이메일",
    path: "/counselor/counselingEmail",
    upperId: 2,
    depth: 2,
    seq: 4,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 7,
    name: "QnA",
    path: "/counselor/counselingQna",
    upperId: 2,
    depth: 2,
    seq: 5,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 8,
    name: "비상담업무",
    path: "/counselor/noticeBoard",
    upperId: 2,
    depth: 2,
    seq: 6,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 9,
    name: "상담 리스트",
    path: "",
    upperId: 0,
    depth: 1,
    seq: 3,
    useFlag: 1,
    isLeaf: 0,
    centerId: 0,
  },
  {
    id: 10,
    name: "티켓 리스트",
    path: "/counselor/list/ticketList",
    upperId: 9,
    depth: 2,
    seq: 1,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 11,
    name: "상담 리스트",
    path: "/counselor/list/historyList",
    upperId: 9,
    depth: 2,
    seq: 2,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 12,
    name: "업무 이관 리스트",
    path: "/counselor/list/transferList",
    upperId: 9,
    depth: 2,
    seq: 3,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 13,
    name: "상담 채널 리스트",
    path: "/counselor/list/sms",
    upperId: 9,
    depth: 2,
    seq: 4,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 14,
    name: "상담 채널 통계",
    path: "/counselor/list/sms/statistics",
    upperId: 9,
    depth: 2,
    seq: 5,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 15,
    name: "이메일상담 리스트",
    path: "/counselor/list/email",
    upperId: 9,
    depth: 2,
    seq: 6,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 16,
    name: "QnA상담 리스트",
    path: "/counselor/list/qna",
    upperId: 9,
    depth: 2,
    seq: 7,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 17,
    name: "게시판상담 리스트",
    path: "/counselor/list/board",
    upperId: 9,
    depth: 2,
    seq: 8,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 18,
    name: "콜백",
    path: "",
    upperId: 0,
    depth: 1,
    seq: 4,
    useFlag: 0,
    isLeaf: 0,
    centerId: 0,
  },
  {
    id: 19,
    name: "콜백조회",
    path: "/callback/search",
    upperId: 18,
    depth: 2,
    seq: 1,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 20,
    name: "콜백분배",
    path: "/callback/distribution",
    upperId: 18,
    depth: 2,
    seq: 2,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 21,
    name: "큐포기호조회",
    path: "/callback/queueAbandon",
    upperId: 18,
    depth: 2,
    seq: 3,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 22,
    name: "일정 관리",
    path: "/schedule",
    upperId: 0,
    depth: 1,
    seq: 5,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 23,
    name: "캠페인",
    path: "",
    upperId: 0,
    depth: 1,
    seq: 6,
    useFlag: 0,
    isLeaf: 0,
    centerId: 0,
  },
  {
    id: 24,
    name: "캠페인",
    path: "/campaign/list",
    upperId: 23,
    depth: 2,
    seq: 1,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 25,
    name: "리스트 업로드",
    path: "/campaign/upload",
    upperId: 23,
    depth: 2,
    seq: 2,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 26,
    name: "리스트 할당",
    path: "/campaign/assign",
    upperId: 23,
    depth: 2,
    seq: 3,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 27,
    name: "캠페인 설문 관리",
    path: "/campaign/survey",
    upperId: 23,
    depth: 2,
    seq: 4,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 28,
    name: "리스트별 개별 할당",
    path: "/campaign/assignEach",
    upperId: 23,
    depth: 2,
    seq: 5,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 29,
    name: "캠페인 설문 결과",
    path: "/campaign/result",
    upperId: 23,
    depth: 2,
    seq: 6,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 30,
    name: "고객조회LOG",
    path: "/customer/log",
    upperId: 0,
    depth: 1,
    seq: 7,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 31,
    name: "상담사 관리",
    path: "/employee",
    upperId: 0,
    depth: 1,
    seq: 8,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
    url: "/counsel/list",
  },
  {
    id: 33,
    name: "U Admin",
    path: "",
    upperId: 0,
    depth: 1,
    seq: 10,
    useFlag: 1,
    isLeaf: 1,
    centerId: 0,
    url: "https://jedai-qa-web.nexuscommunity.net/admin",
  },
  {
    id: 34,
    name: "U Analyzer",
    path: "/analyzer",
    upperId: 0,
    depth: 1,
    seq: 11,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
  {
    id: 35,
    name: "AI 교육서비스",
    path: "/education",
    upperId: 0,
    depth: 1,
    seq: 12,
    useFlag: 0,
    isLeaf: 1,
    centerId: 0,
  },
];