/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MenuAgentDTO
 */
export interface MenuAgentDTO {
    /**
     * 
     * @type {number}
     * @memberof MenuAgentDTO
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof MenuAgentDTO
     */
    'centerId'?: number;
    /**
     * 
     * @type {number}
     * @memberof MenuAgentDTO
     */
    'upperId'?: number;
    /**
     * 
     * @type {number}
     * @memberof MenuAgentDTO
     */
    'seq'?: number;
    /**
     * 
     * @type {string}
     * @memberof MenuAgentDTO
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof MenuAgentDTO
     */
    'path'?: string;
    /**
     * 
     * @type {number}
     * @memberof MenuAgentDTO
     */
    'depth'?: number;
    /**
     * 
     * @type {number}
     * @memberof MenuAgentDTO
     */
    'useFlag'?: number;
    /**
     * 
     * @type {number}
     * @memberof MenuAgentDTO
     */
    'isLeaf'?: number;
}

